package com.db.manager;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hu.layaliprokect.Entity.QylEntity;
import com.example.hu.layaliprokect.Entity.TaskEntity;

import com.db.manager.QylEntityDao;
import com.db.manager.TaskEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig qylEntityDaoConfig;
    private final DaoConfig taskEntityDaoConfig;

    private final QylEntityDao qylEntityDao;
    private final TaskEntityDao taskEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        qylEntityDaoConfig = daoConfigMap.get(QylEntityDao.class).clone();
        qylEntityDaoConfig.initIdentityScope(type);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        qylEntityDao = new QylEntityDao(qylEntityDaoConfig, this);
        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);

        registerDao(QylEntity.class, qylEntityDao);
        registerDao(TaskEntity.class, taskEntityDao);
    }
    
    public void clear() {
        qylEntityDaoConfig.clearIdentityScope();
        taskEntityDaoConfig.clearIdentityScope();
    }

    public QylEntityDao getQylEntityDao() {
        return qylEntityDao;
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

}
