package com.db.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.hu.layaliprokect.Entity.QylEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QYL_ENTITY".
*/
public class QylEntityDao extends AbstractDao<QylEntity, Long> {

    public static final String TABLENAME = "QYL_ENTITY";

    /**
     * Properties of entity QylEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, long.class, "key", false, "KEY");
        public final static Property CurrentLi = new Property(2, float.class, "currentLi", false, "CURRENT_LI");
        public final static Property MaxLi = new Property(3, float.class, "maxLi", false, "MAX_LI");
        public final static Property TestingNum = new Property(4, Integer.class, "testingNum", false, "TESTING_NUM");
        public final static Property IsSave = new Property(5, boolean.class, "isSave", false, "IS_SAVE");
        public final static Property QylCreateTime = new Property(6, String.class, "qylCreateTime", false, "QYL_CREATE_TIME");
    }


    public QylEntityDao(DaoConfig config) {
        super(config);
    }
    
    public QylEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QYL_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"KEY\" INTEGER NOT NULL ," + // 1: key
                "\"CURRENT_LI\" REAL NOT NULL ," + // 2: currentLi
                "\"MAX_LI\" REAL NOT NULL ," + // 3: maxLi
                "\"TESTING_NUM\" INTEGER," + // 4: testingNum
                "\"IS_SAVE\" INTEGER NOT NULL ," + // 5: isSave
                "\"QYL_CREATE_TIME\" TEXT);"); // 6: qylCreateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QYL_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QylEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
        stmt.bindDouble(3, entity.getCurrentLi());
        stmt.bindDouble(4, entity.getMaxLi());
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(5, testingNum);
        }
        stmt.bindLong(6, entity.getIsSave() ? 1L: 0L);
 
        String qylCreateTime = entity.getQylCreateTime();
        if (qylCreateTime != null) {
            stmt.bindString(7, qylCreateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QylEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
        stmt.bindDouble(3, entity.getCurrentLi());
        stmt.bindDouble(4, entity.getMaxLi());
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(5, testingNum);
        }
        stmt.bindLong(6, entity.getIsSave() ? 1L: 0L);
 
        String qylCreateTime = entity.getQylCreateTime();
        if (qylCreateTime != null) {
            stmt.bindString(7, qylCreateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public QylEntity readEntity(Cursor cursor, int offset) {
        QylEntity entity = new QylEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // key
            cursor.getFloat(offset + 2), // currentLi
            cursor.getFloat(offset + 3), // maxLi
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // testingNum
            cursor.getShort(offset + 5) != 0, // isSave
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // qylCreateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QylEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getLong(offset + 1));
        entity.setCurrentLi(cursor.getFloat(offset + 2));
        entity.setMaxLi(cursor.getFloat(offset + 3));
        entity.setTestingNum(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setIsSave(cursor.getShort(offset + 5) != 0);
        entity.setQylCreateTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(QylEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(QylEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(QylEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
